version: "3"
services:
  api:
    #  image:node:18
    image: pi:3
    build: .
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongo
      - PORT=9090
    ports:
      - 9090:9090
    networks:
      - app7
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    ports:
      - "9091:27017"
    volumes:
      - database:/data/db
    networks:
      - app7
volumes:
  database:
networks:
  app7:
